name: Build and Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ develop ]
    tags: [ v* ]
    paths:
      - .github/workflows/mkdocs.yml
      - docs/**

  workflow_dispatch:

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ§° Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      - name: ğŸ”¨ Install rzk proof assistant
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: fizruk/rzk
          tag: latest # FIXME: should use the version from the same Git commit
          rename-to: rzk
          chmod: 0755

      - name: ğŸ”¨ Install Pygments lexer for rzk
        run: pip install rzk/RzkLexer

      - name: ğŸ”¨ Install MkDocs Material and mike
        run: pip install -r docs/requirements.txt

      - name: âš™ï¸  Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: ğŸš€ Deploy with mike (${{ github.ref_name }}, latest)
        if: ${{ github.ref_name != 'develop' }}
        run: |
          mike deploy --rebase --push --config-file docs/mkdocs.yml ${{ github.ref_name }} latest

      - name: ğŸš€ Deploy with mike (${{ github.ref_name }})
        if: ${{ github.ref_name == 'develop' }}
        run: |
          mike deploy --rebase --push --config-file docs/mkdocs.yml ${{ github.ref_name }}

